# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GuczhNW4pno3pSm1UnI1vn2X_jngBZbs
"""

import numpy as np
from scipy.stats import bernoulli as brn

number_of_simulations = int(5e7)
prob_positive_report = 0.01
prob_negative_report = 1 - prob_positive_report
data_cases = brn.rvs(size = number_of_simulations, p = prob_negative_report)
#0 represents positive report
#1 represents negative report
prob_positive_incorrect = 12/100
prob_negative_incorrect = 15/100
data_positive_incorrect = brn.rvs(size = number_of_simulations, p = prob_positive_incorrect)
data_negative_incorrect = brn.rvs(size = number_of_simulations, p = prob_negative_incorrect)
#0 represents correct report
#1 represents incorrect report
count_incorrect = 0
for i in range(number_of_simulations):
  if data_cases[i] == 0 and data_positive_incorrect[i] == 1:
    count_incorrect += 1
  if data_cases[i] == 1 and data_negative_incorrect[i] == 1:
    count_incorrect += 1

prob_incorrect = count_incorrect / number_of_simulations
prob_theoretical_incorrect = prob_positive_report*prob_positive_incorrect + prob_negative_report*prob_negative_incorrect
error_prob = abs(prob_theoretical_incorrect - prob_incorrect)
print("The theoretical probability obtained is: {}".format(prob_theoretical_incorrect))
print("The probability obtained from simulations is: {}".format(prob_incorrect))
print("The error in calculating the probability is: {}".format(error_prob))
print("As the error is extremely small, we can conclude that both the results are approximately the same")