# -*- coding: utf-8 -*-
"""chapro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fl9muHV0Pz8Ttxc04ioBVfzJHI_m2Oaf
"""

import random as rd
import numpy as np

n = int(input("Enter size of matrix "))
count = 0
sample_size = 1000000
for a in range(sample_size):
  matrix = []
  for i in range(n):
    row = []
    for j in range(n):
      value = rd.randint(0, 1)
      row.append(value)
    matrix.append(row)
  det = np.linalg.det(matrix)
    
  if det > 0:
    count += 1
prob = count / sample_size
print(prob)